name: Build Mdc builder image

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with: 
        images:  ghcr.io/gythialy/mdc-builder
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          # type=semver,pattern={{version}}
          # type=semver,pattern={{major}}.{{minor}}
          # type=semver,pattern={{major}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.builder
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max        
    - name: Commit and push if changed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        echo -e "$(curl https://api.github.com/repos/yoshiko2/Movie_Data_Capture/releases/latest -s | jq .name -r)" > VERSION
        git remote set-url origin https://${GITHUB_TOKEN}@github.com/gythialy/mdc-docker.git
        git diff
        git config --global user.email "gythialy.koo+github@gmail.com"
        git config --global user.name "Commiter Bot"
        git add -A
        git commit -m "🚀 Update MDC version $(cat VERSION)" || exit 0
        git push