name: Docker Image CI

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      git-tag:
        description: mdc tag, with default value `6.5.1`

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Set up version args
      id: args
      run: |
        echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with: 
        images:  ghcr.io/gythialy/mdc
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=v${{ env.VERSION }}
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        # platforms: linux/amd64,linux/arm64
        build-args: |
          MDC_TAG=${{ github.event.inputs.git-tag || env.VERSION || '6.5.1' }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max